const $ = (s) => document.querySelector(s);
const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
let data = null;
function toast(message){ const node=$("#toast"); node.textContent=message; node.classList.add("show"); clearTimeout(toast.timer); toast.timer=setTimeout(()=>node.classList.remove("show"),2400); }
async function api(action,payload){ const options=payload?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}:{}; const res=await fetch(`/merchant_api.php?action=${encodeURIComponent(action)}`,options); const json=await res.json().catch(()=>({ok:false,error:"bad json"})); if(!res.ok||!json.ok) throw new Error(json.error||`API ${action} failed`); return json; }
function money(v){ return `¥${Number(v||0).toLocaleString("zh-CN")}`; }
function render(){ const m=data.merchant||{}; const plan=data.currentPlan||{}; const metrics=data.metrics||[]; const orders=data.orders||[]; $("#merchantName").textContent=m.name||"商户后台"; $("#merchantDesc").textContent=`当前套餐：${plan.name||"未开通"}，有效期至 ${m.expiresAt||"-"}`; $("#merchantStats").innerHTML=[["当前套餐",esc(plan.name||"未开通"),"服务状态","badge-success"],["关键词额度",`${m.usedKeywords||0}/${plan.keywords||0}`,"已用/总量","badge-info"],["有效期",esc(m.expiresAt||"-"),esc(m.status||"待开通"),"badge-warning"],["支付通道",data.payment?.enabled?"已配置":"待配置","支付网关","badge-secondary"]].map(([a,b,c,d])=>`<article class="card stat-card"><div class="stat-top"><span>${a}</span><span class="badge ${d}">${esc(c)}</span></div><strong>${b}</strong><p>商户独立后台数据</p></article>`).join(''); $("#merchantPanel").innerHTML=`<div class="card-header"><div><h2>套餐续费</h2><p>购买或续费套餐后，支付成功回调会自动延长有效期。</p></div><span class="badge badge-info">商户</span></div><div class="merchant-summary">${metrics.map(x=>`<article class="metric-card"><span>${esc(x.metric)}</span><strong>${esc(x.value)}</strong><p>${esc(x.desc)}</p><em>${esc(x.trend)}</em></article>`).join('')}</div><div class="plan-grid">${(data.plans||[]).map(p=>`<article class="plan-card"><div><strong>${esc(p.name)}</strong><span class="badge badge-outline">${esc(p.billing)}</span></div><p>${esc((p.platforms||[]).join('、'))}</p><div class="plan-price">${money(p.price)}<span> / ${esc(p.billing)}</span></div><p>${esc(p.keywords)} 个关键词，${esc(p.durationDays)} 天服务期</p><button class="btn btn-primary" data-renew="${esc(p.id)}">续费/购买</button></article>`).join('')}</div><section class="business-card"><div class="section-title"><div><h3>购买记录</h3><p>下单后如返回支付链接，将自动打开收银台。</p></div></div><div class="merchant-list">${orders.map(o=>`<article class="merchant-row"><div><strong>${esc(o.mchOrderNo||o.id||"订单")}</strong><p>${esc(o.createdAt||'')}</p></div><span>${money(o.amount)}</span><span class="badge badge-outline">${esc(o.status)}</span>${o.payUrl?`<a class="btn btn-outline" href="${esc(o.payUrl)}" target="_blank" rel="noreferrer">继续支付</a>`:''}</article>`).join('')||'<p class="empty-note">暂无购买记录</p>'}</div></section>`; }
async function load(){ data=await api('dashboard'); render(); }
document.addEventListener('click',async(e)=>{ const renew=e.target.closest('[data-renew]'); if(renew){ try{ const result=await api('renewPlan',{planId:renew.dataset.renew}); toast(result.paymentEnabled?'已创建支付订单':'已创建订单，支付参数待配置'); if(result.order?.payUrl) window.open(result.order.payUrl,'_blank','noopener'); await load(); }catch(err){ console.error(err); toast(err.message||'续费失败'); } } });
$("#refreshBtn").addEventListener('click',load); $("#logoutBtn").addEventListener('click',()=>{ location.href='/merchant.php?logout=1'; });
load().catch(err=>{ console.error(err); toast('商户数据加载失败'); });
